apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mongodbServiceName }}
spec:
  selector:
    app: {{ .Values.mongoName }}
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
